### ISSUE TITLE
"The enviroment variables are empty."

### ISSUE THREAD

**Issue by AustinGil** [berrysauce/microletter#7]
Seems like environment variables are required but not included. The SMPT test fails as well as the newsletter sign up.

![image](https://user-images.githubusercontent.com/4879075/127512250-21e79e08-3c77-4741-8efa-a442e4d9d92b.png)

![image](https://user-images.githubusercontent.com/4879075/127512279-e9ba61c5-fa18-4262-b92e-25b4ff6ff229.png)

**Comment by berrysauce** [comment]
Hey 👋 This is not a bug. To use microletter, you need to get the SMTP credentials of your preferred email provider (Gmail, Namecheap, etc.). You can find out what you need and how to find it [here](https://docs.microletter.cc/guides/how-to-get-your-smtp-credentials). If you've collected the credentials, you need to add them to your microletter instance like shown by [this guide](https://docs.microletter.cc/guides/getting-started).

**Comment by AustinGil** [comment]
Ahh, I did not see that. Thank you.

**Comment by berrysauce** [comment]
Yeah, I think I'll make that a bit clearer in the next update!
